import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import {
  Sparkles,
  FileText,
  Image as ImageIcon,
  Video,
  Wand2,
  Copy,
  Download,
  Send,
  Loader2,
  Check,
  RefreshCw,
  Settings,
  Zap
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  fadeInUp,
  fadeInScale,
  staggerContainer,
  staggerItem
} from "@/lib/animations";

const ContentGenerator = () => {
  const [prompt, setPrompt] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [selectedClient, setSelectedClient] = useState("");
  const [contentType, setContentType] = useState("blog");
  const [tone, setTone] = useState("professional");

  const contentTypes = [
    {
      id: "blog",
      label: "Blog Post",
      icon: FileText,
      description: "Long-form articles and guides",
    },
    {
      id: "social",
      label: "Social Media",
      icon: ImageIcon,
      description: "Engaging social posts",
    },
    {
      id: "email",
      label: "Email",
      icon: Send,
      description: "Marketing emails and newsletters",
    },
    {
      id: "video",
      label: "Video Script",
      icon: Video,
      description: "YouTube and video scripts",
    },
  ];

  const tones = [
    { id: "professional", label: "Professional" },
    { id: "casual", label: "Casual" },
    { id: "friendly", label: "Friendly" },
    { id: "authoritative", label: "Authoritative" },
    { id: "persuasive", label: "Persuasive" },
  ];

  const clients = [
    { id: "1", name: "Tech Startup Inc" },
    { id: "2", name: "Marketing Agency Co" },
    { id: "3", name: "E-commerce Store" },
  ];

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGeneratedContent("");

    // Simulate AI generation (replace with actual API call)
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const mockContent = `# ${prompt}\n\n## Introduction\n\nThis is a professionally crafted ${contentType} that addresses your topic with a ${tone} tone. The content is optimized for engagement and conversion.\n\n## Key Points\n\n- Engaging opening that hooks the reader\n- Well-structured body with clear sections\n- Compelling call-to-action\n- SEO-optimized throughout\n\n## Main Content\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\n\n## Conclusion\n\nThis content is ready to publish and will help drive engagement with your audience. Feel free to customize it further to match your specific needs.\n\n---\n\n*Generated by Publisphere AI*`;

    setGeneratedContent(mockContent);
    setIsGenerating(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-7xl mx-auto p-8">
        {/* Header */}
        <motion.div
          initial="hidden"
          animate="visible"
          variants={fadeInUp}
          className="mb-8"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-foreground/5 border border-foreground/10 rounded-xl animate-pulse-subtle">
              <Sparkles className="h-8 w-8 text-foreground" />
            </div>
            <div>
              <h1 className="text-4xl font-bold">AI Content Generator</h1>
              <p className="text-muted-foreground text-lg">
                Create professional content in seconds with AI
              </p>
            </div>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Configuration Panel */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 }}
            className="lg:col-span-1 space-y-6"
          >
            {/* Content Type Selection */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Wand2 className="h-5 w-5" />
                Content Type
              </h3>
              <div className="space-y-2">
                {contentTypes.map((type) => {
                  const Icon = type.icon;
                  return (
                    <motion.button
                      key={type.id}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                      onClick={() => setContentType(type.id)}
                      className={`w-full text-left p-4 rounded-lg border transition-all ${
                        contentType === type.id
                          ? "bg-foreground/5 border-foreground/20"
                          : "bg-card border-border hover:bg-muted/50"
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <div
                          className={`p-2 rounded-lg ${
                            contentType === type.id
                              ? "bg-foreground/10"
                              : "bg-muted"
                          }`}
                        >
                          <Icon className="h-4 w-4" />
                        </div>
                        <div className="flex-1">
                          <div className="font-medium mb-0.5">{type.label}</div>
                          <div className="text-xs text-muted-foreground">
                            {type.description}
                          </div>
                        </div>
                        {contentType === type.id && (
                          <Check className="h-4 w-4 text-foreground" />
                        )}
                      </div>
                    </motion.button>
                  );
                })}
              </div>
            </Card>

            {/* Settings */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Settings className="h-5 w-5" />
                Settings
              </h3>
              <div className="space-y-4">
                {/* Client Selection */}
                <div>
                  <Label htmlFor="client" className="mb-2">
                    Select Client
                  </Label>
                  <select
                    id="client"
                    value={selectedClient}
                    onChange={(e) => setSelectedClient(e.target.value)}
                    className="w-full px-3 py-2 bg-background border border-border rounded-lg focus:ring-2 focus:ring-foreground/20 focus:outline-none"
                  >
                    <option value="">Choose a client...</option>
                    {clients.map((client) => (
                      <option key={client.id} value={client.id}>
                        {client.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Tone Selection */}
                <div>
                  <Label className="mb-2">Tone of Voice</Label>
                  <div className="flex flex-wrap gap-2">
                    {tones.map((t) => (
                      <Button
                        key={t.id}
                        variant={tone === t.id ? "default" : "outline"}
                        size="sm"
                        onClick={() => setTone(t.id)}
                      >
                        {t.label}
                      </Button>
                    ))}
                  </div>
                </div>
              </div>
            </Card>

            {/* Quick Tips */}
            <Card className="p-6 bg-gradient-bg-animate">
              <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <Zap className="h-4 w-4" />
                Pro Tips
              </h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>• Be specific about your topic</li>
                <li>• Include target keywords</li>
                <li>• Mention desired word count</li>
                <li>• Specify your target audience</li>
              </ul>
            </Card>
          </motion.div>

          {/* Generation Panel */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="lg:col-span-2 space-y-6"
          >
            {/* Prompt Input */}
            <Card className="p-6">
              <Label htmlFor="prompt" className="text-lg font-semibold mb-4 block">
                What would you like to create?
              </Label>
              <Textarea
                id="prompt"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Example: Write a 1000-word blog post about sustainable marketing practices for eco-conscious brands..."
                className="min-h-[120px] mb-4 focus-ring"
                disabled={isGenerating}
              />
              <div className="flex items-center gap-3">
                <Button
                  onClick={handleGenerate}
                  disabled={!prompt.trim() || isGenerating}
                  className="btn-premium gap-2 flex-1"
                  size="lg"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-5 w-5" />
                      Generate Content
                    </>
                  )}
                </Button>
                {generatedContent && (
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={() => setGeneratedContent("")}
                    className="gap-2"
                  >
                    <RefreshCw className="h-4 w-4" />
                    Clear
                  </Button>
                )}
              </div>
            </Card>

            {/* Generated Content */}
            <AnimatePresence>
              {(isGenerating || generatedContent) && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.3 }}
                >
                  <Card className="p-6">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="text-lg font-semibold flex items-center gap-2">
                        <FileText className="h-5 w-5" />
                        Generated Content
                      </h3>
                      {generatedContent && (
                        <div className="flex items-center gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={handleCopy}
                            className="gap-2"
                          >
                            {copied ? (
                              <>
                                <Check className="h-4 w-4" />
                                Copied!
                              </>
                            ) : (
                              <>
                                <Copy className="h-4 w-4" />
                                Copy
                              </>
                            )}
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            className="gap-2"
                          >
                            <Download className="h-4 w-4" />
                            Export
                          </Button>
                          <Button size="sm" className="gap-2">
                            <Send className="h-4 w-4" />
                            Publish
                          </Button>
                        </div>
                      )}
                    </div>

                    {isGenerating ? (
                      <div className="space-y-3">
                        <div className="skeleton h-6 w-3/4" />
                        <div className="skeleton h-4 w-full" />
                        <div className="skeleton h-4 w-full" />
                        <div className="skeleton h-4 w-5/6" />
                        <div className="skeleton h-6 w-2/3 mt-6" />
                        <div className="skeleton h-4 w-full" />
                        <div className="skeleton h-4 w-full" />
                        <div className="skeleton h-4 w-4/5" />
                      </div>
                    ) : (
                      <div className="prose prose-sm max-w-none">
                        <div className="p-4 bg-muted/30 border border-border rounded-lg font-mono text-sm whitespace-pre-wrap custom-scrollbar max-h-[600px] overflow-y-auto">
                          {generatedContent}
                        </div>
                      </div>
                    )}
                  </Card>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Empty State */}
            {!isGenerating && !generatedContent && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
              >
                <Card className="p-12">
                  <div className="empty-state">
                    <div className="p-6 bg-gradient-bg-animate border border-border rounded-full w-fit mx-auto mb-6 animate-bounce-subtle">
                      <Sparkles className="h-12 w-12 text-foreground" />
                    </div>
                    <h3 className="text-2xl font-semibold mb-2">
                      Ready to create magic? ✨
                    </h3>
                    <p className="text-muted-foreground mb-6 max-w-md">
                      Enter your content brief above and let our AI create
                      professional, engaging content in seconds.
                    </p>
                  </div>
                </Card>
              </motion.div>
            )}
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default ContentGenerator;
